branch-defaults:
  client-database-deployment:
    environment: twoge-rds-db-deployment
    group_suffix: null
global:
  application_name: twoge-rds-db
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
